# -*- coding: utf-8 -*-
"""Untitled27.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MiN7jSHilt81_-Zk9lLA1vc8G9VxmgT3
"""

!pip install python-pptx

from pptx import Presentation
from pptx.util import Inches
from pptx.dml.color import RGBColor
from pptx.enum.text import PP_ALIGN
from pptx.util import Pt
from pptx.oxml.ns import nsdecls
from pptx.oxml import parse_xml

# Read content from a text file
def read_text_file(file_path):
    with open(file_path, 'r') as file:
        content = file.read()
    return content

# Create a new slide with content and font styles
def create_slide(prs, content, font_file):
    slide_layout = prs.slide_layouts[1]  # Use the appropriate layout (1 for Title and Content)
    slide = prs.slides.add_slide(slide_layout)

    # Set font styles for the slide
    for shape in slide.shapes:
        if shape.has_text_frame:
            for paragraph in shape.text_frame.paragraphs:
                for run in paragraph.runs:
                    # Load the font file
                    run.font.file = font_file
                    run.font.embed = True

    # Add content to the slide
    content_frame = slide.shapes[1].text_frame
    content_frame.text = content
    content_frame.text = content

    return prs

# Create a new PowerPoint presentation
prs = Presentation()

# Read content from sample_slide1_input.txt and add to Slide 1
slide1_content = read_text_file('sample_slide1_input.txt')
prs = create_slide(prs, slide1_content, 'sample_font_file.ttf')

# Read content from sample_slide2_input.txt and add to Slide 2
slide2_content = read_text_file('sample_slide2_input.txt')
prs = create_slide(prs, slide2_content, 'sample_font_file.ttf')

# Save the presentation
prs.save('output.pptx')
print("Presentation created successfully.")

